### ISSUE TITLE
Split files are having are named as filename-blessed1.css, etc.

### ISSUE THREAD

**Issue by josephnvn** [adam-lynch/gulp-bless#16]
hi,

Is there anyway to target the suffixed name for split file, from being 'blessed' to something from options?
may be options.splitname 

I just updated the plugin to do this...
blessedFiles.forEach(function (blessedFile) {
     // overwrite the name of the file...
     blessedFile.filename = blessedFile.filename.replace('blessed', options.splitname);
     stream.push(new File({ ...
....
});

Would you consider this functionality for your next release.

Thanks,
J

**Comment by adam-lynch** [comment]
Hey Joseph,

I was just replying to your email now but then I saw this.

I'd suggest using gulp-rename. So you'd have something like:

```javascript
//...
var rename = require('gulp-rename');

gulp.task('default', function(){
    gulp.src('*.css')
        .pipe(rename('blessed', 'whatever'))
        .pipe(gulp.dest('./destinationDirectory'));
});
```

**Comment by josephnvn** [comment]
hi Adam,

 Thanks for the reply.

 I have given it a try. Rename has to happen after the .css file physically
becomes available and therefore has to follow as a sequential task after
bless. In my project I am looping tasks for multiple projects on single
function. It would be ideal if gulp-bless could support it.

*Check my code below. *
Config is a build json file with style sheets combinations etc...


for(var i=0; i<config.styles.length; i++ ) {
                $.sass( config.styles[i].src, {
                        compass: true,
                        style: 'expanded',
                        imports: false,
                        container : config.styles[i].src.replace(/[^\/]*$/,
''),
                        loadPath : '.'
                    })
                    .on('error', function (err) {
                        console.error('Error!', err.message);
                    })
                    .pipe($.autoprefixer("last 3 version", "safari 5", "ie
8", "ie 9"))
                    .pipe($.bless({
                        compress : true,
                        imports: false,
                        log: true,
                        splitname: 'part'
                    }))
                    .pipe(taskName != "watch" ? $.minifyCss() :
$.util.noop())
                    .pipe(gulp.dest(config.styles[i].dist))
                    .on('end', function() {
                        $.log( projectName + ' sass files compliled',
'completed');
                    });
            }




Cheers,
J

On 8 June 2015 at 12:14, Adam Lynch <notifications@github.com> wrote:

> Hey Joseph,
>
> I was just replying to your email now but then I saw this.
>
> I'd suggest using gulp-rename. So you'd have something like:
>
> //...var rename = require('gulp-rename');
>
> gulp.task('default', function(){
>     gulp.src('*.css')
>         .pipe(rename('blessed', 'whatever'))
>         .pipe(gulp.dest('./destinationDirectory'));
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adam-lynch/gulp-bless/issues/16#issuecomment-109953895>
> .
>



-- 
With Regards,
Joseph Peeka
Flex/Flash/Web Designer/developer
www.optikos-interactivity.co.uk

**Comment by adam-lynch** [comment]
I don't see the problem with using gulp-rename there. What happens which isn't correct?

If you use gulp-debug and put `.pipe($.debug())` after the gulp-bless pipe, is the number of files correct?

**Comment by josephnvn** [comment]
Thanks Adam...
WORKS now! 
rename usage was a bit different ...

                    .pipe($.rename(function (path) {
                        path.basename = path.basename.replace('blessed', 'part');
                    }))

**Comment by adam-lynch** [comment]
Ah ok, sorry my bad.
