### ISSUE TITLE
Removes outer media queries if they contain nested media queries

### ISSUE THREAD

**Issue by cholawo** [adam-lynch/gulp-bless#17]
I give gulp bless (3.0.1) a file containing nested media queries
...

    @media (min-width: 60em) {
        // my styles..

        // a mixin that I've included might nest another media query inside
        @media (min-width: 30em) {
            // its styles
        }
    }

...

Gulp bless removes the outer media query.

I'm surprised it was bless because I thought it just counted selectors and then split. My css file doesn't currently need splitting so I'm just comparing a minified and a blessed file.

**Comment by adam-lynch** [comment]
Weird, I've never had that problem myself. This gulp plugin is just a wrapper for https://github.com/paulyoung/bless.js. Could you open an issue there? (Unless you're sure the problem is with gulp-bless and not bless, then I'll reopen this)
